service:
  name: sqs-mayhem

provider:
  name: aws

resources:
  Resources:
    SqsMayhemQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: MayhemQueue
        ReceiveMessageWaitTimeSeconds: 10
        VisibilityTimeout: 120
    SqsMayhemRdsCluster:
      Type: AWS::RDS::DBCluster
      Properties:
        MasterUsername: ${opt:user}
        MasterUserPassword: ${opt:password}
        DBClusterIdentifier: sqs-mayhem-cluster
        Engine: aurora-postgresql
        EngineVersion: "10.7"
        EngineMode: serverless
        ScalingConfiguration:
          AutoPause: true
          MinCapacity: 4
          MaxCapacity: 32
          SecondsUntilAutoPause: 300

  Outputs:
    QueueArn:
      Value:
        !GetAtt SqsMayhemQueue.Arn
    QueueName:
      Value:
        !GetAtt SqsMayhemQueue.QueueName
    RdsEnpointAddress:
      Value:
        !GetAtt SqsMayhemRdsCluster.Endpoint.Address